debezium/debezium-connector-vitess

- pom.xml
https://issues.redhat.com/browse/DBZ-2611
> DBZ-2611 Provide separate project version for releases

- documentation/config/sample_multi_shard_vitess_connector_config.json
- documentation/config/sample_single_shard_vitess_connector_config.json
- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
- src/test/docker/Dockerfile
- src/test/docker/local/create_tables_sharded.sql
- src/test/docker/local/create_tables_unsharded.sql
- src/test/docker/local/initial_cluster.sh
- src/test/docker/local/vschema_tables_unsharded.json
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-2749
> DBZ-2749 Upgrade vitess docker image to use vitess v8.0.0 GA

- src/main/java/io/debezium/connector/vitess/VitessType.java
- src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolver.java
- src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
- src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
- src/test/java/io/debezium/connector/vitess/TestHelper.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
- src/test/resources/vitess_create_tables.ddl
https://issues.redhat.com/browse/DBZ-2776
> DBZ-2776 Add support for unsigned integer types

- README.md
https://issues.redhat.com/browse/DBZ-2802
> DBZ-2802 Fix build status badge in README.md

- src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-2836
> DBZ-2836 Invalid column name should fail connector with meaningful message

- src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
https://issues.redhat.com/browse/DBZ-2873
> DBZ-2873 Add more comprehensible logs to FIELD event

- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-2851
Vitess Connector already supports the `sanitize.field.names` configuration. I've added an integration test in this PR.
Documentation is added in another [PR](https://github.com/debezium/debezium/pull/2031).
> DBZ-2851 Add integration test for `sanitize.field.names` config

- pom.xml
https://issues.redhat.com/browse/DBZ-2892
Depends on https://github.com/debezium/debezium/pull/2038
> DBZ-2892 Align deps with Connect runtime and remove unused

- src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolver.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-2906
> DBZ-2906 Sanitise DECIMAL string from VStream

- .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-3012
> DBZ-3012 Ignore .md files while building CI

- src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
- src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
- src/test/resources/vitess_create_tables.ddl
https://issues.redhat.com/browse/DBZ-3115
> DBZ-3115 Add integration test for JSON column

- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
https://issues.redhat.com/browse/DBZ-3132
> DBZ-3132 Exclude CommonConnectorConfig.PROVIDE_TRANSACTION_METADATA

- pom.xml
- src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
https://issues.redhat.com/browse/DBZ-3115
> DBZ-3115 Fix test failure due to unstable json key order

- .github/workflows/sanity-check.yml
https://issues.redhat.com/browse/DBZ-3152
> DBZ-3152 Set up commit message check for pull-requests

- src/main/java/io/debezium/connector/vitess/VitessConnector.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
https://issues.redhat.com/browse/DBZ-3117
> DBZ-3117 Config validation for Vitess

- src/main/java/io/debezium/connector/vitess/VitessDatabaseSchema.java
Introduced by https://github.com/debezium/debezium/pull/2182
> DBZ-3141 Change privileges according to parent class

- src/main/java/io/debezium/connector/vitess/Filters.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/main/java/io/debezium/connector/vitess/VitessDatabaseSchema.java
https://issues.redhat.com/browse/DBZ-3271
Requires https://github.com/debezium/debezium/pull/2211/
> DBZ-3271 Centralizing column filter handling

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
- src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
- src/test/java/io/debezium/connector/vitess/connection/VitessReplicationConnectionIT.java
https://issues.redhat.com/browse/DBZ-2511
> DBZ-2511 Dedicated logger for schema name adjuster

- README.md
- pom.xml
https://issues.redhat.com/browse/DBZ-3449
> DBZ-3449 Adding 'quick' profile

- src/main/java/io/debezium/connector/vitess/VitessChangeEventSourceFactory.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
- src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
See [DBZ-2975](https://issues.redhat.com/browse/DBZ-2975).
This PR complements https://github.com/debezium/debezium/pull/2283.
**TODO**:
> DBZ-2975: Extract offset context from object states to method signatures

- src/main/java/io/debezium/connector/vitess/VitessChangeEventSourceFactory.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
- src/main/java/io/debezium/connector/vitess/VitessPartition.java
- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
- src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
- src/test/java/io/debezium/connector/vitess/VitessPartitionTest.java
See [DBZ-2975](https://issues.redhat.com/browse/DBZ-2975).
This PR complements https://github.com/debezium/debezium/pull/2487.
**TODO**:
> DBZ-2975: Add partition awareness to source task components

- src/main/java/io/debezium/connector/vitess/VitessChangeRecordEmitter.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
- src/main/java/io/debezium/connector/vitess/VitessPartition.java
- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
- src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
- src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
- src/test/java/io/debezium/connector/vitess/VitessOffsetContextTest.java
See [DBZ-2975](https://issues.redhat.com/browse/DBZ-2975).
This PR complements https://github.com/debezium/debezium/pull/2546.
**TODO**:
> DBZ-2975: Remove partition from offset context

- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
- src/test/resources/log4j.properties
https://issues.redhat.com/browse/DBZ-3863
> DBZ-3863 Start DMLs afte GTID is obtained

- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-3900
> DBZ-3900 Wait for sharded GTID acquiring

- src/main/java/io/debezium/connector/vitess/VitessChangeEventSourceFactory.java
- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
- src/test/java/io/debezium/connector/vitess/MySQLConnection.java
https://issues.redhat.com/browse/DBZ-2525
> DBZ-2525 Generifying exclusion of columns from snapshotting

- .github/workflows/cross-maven.yml
- .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-3748
> DBZ-3748 Cross CI vitess build on pull request event with debezium core repository

- src/test/java/io/debezium/connector/vitess/VitessConnectorConfigDefTest.java
closes https://issues.redhat.com/browse/DBZ-3943
> DBZ-3943 add ConfigDef test to check for empty or unset `Field#description`

- pom.xml
- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
Closes https://issues.redhat.com/browse/DBZ-4295
> DBZ-4295: Support stop_on_reshard flag

- .github/workflows/cross-maven.yml
- .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-4289
> DBZ-4289 Avoiding superfluous component builds

- pom.xml
https://issues.redhat.com/browse/DBZ-4464
> DBZ-4464 Add missing snapshot repo

- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
Add support for adding extra gRPC headers in the connector config for VStream.
The "vitess.grpc.headers" config takes value in the form of "k1:v1,k2:v2".
This fixes: https://issues.redhat.com/browse/DBZ-4532
> DBZ-4532 Add support for extra gRPC headers

- src/test/docker/Dockerfile
https://issues.redhat.com/browse/DBZ-4559
> DBZ-4559 Use new repo key

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java
Depends on https://github.com/debezium/debezium/pull/3143
> DBZ-4577 Provide custom error message handling

- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
Resolves https://issues.redhat.com/browse/DBZ-4886
> DBZ-4886 Support maxInboundMessageSize config

- src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
https://issues.redhat.com/browse/DBZ-5170
> DBZ-5170 Mysql Commit Timestamp

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessDatabaseSchema.java
- src/main/java/io/debezium/connector/vitess/VitessEventMetadataProvider.java
- src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
- src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
- src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
https://issues.redhat.com/browse/DBZ-4180
> DBZ-4180 Pluggable topic selector

- .github/workflows/cross-maven.yml
- .github/workflows/maven.yml
https://issues.redhat.com/browse/DBZ-5409
> DBZ-5409 Build stable branches for Vitess on push/pull event

- src/main/java/io/debezium/connector/vitess/VitessTopicSelector.java
https://issues.redhat.com/browse/DBZ-5457
> DBZ-5457 Deprecate legacy topic selector for all connectors

- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-5497
> DBZ-5497 Align test behavior

- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
Depends on https://github.com/debezium/debezium/pull/3834
> DBZ-3293 Add signal table automatically to include list

- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
- src/test/java/io/debezium/connector/vitess/TestHelper.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-5043
Changes related to https://github.com/debezium/debezium/pull/3804
> DBZ-5043 Use topix.prefix instead of database.server.name

- src/main/java/io/debezium/connector/vitess/VitessSchemaFactory.java
https://issues.redhat.com/browse/DBZ-5044
> DBZ-5044 Introduce SchemaFactory for Vitess

- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
- src/test/java/io/debezium/connector/vitess/TestHelper.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-5043
> DBZ-5043 Reflect move of TOPIC_PREFIX to CommonConnectorConfig

- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
https://issues.redhat.com/browse/DBZ-5671
> DBZ-5671 Remove logic name parameter from sub connector config

- pom.xml
- src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
- src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
- src/test/java/io/debezium/connector/vitess/VgtidTest.java
- src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
- src/test/java/io/debezium/connector/vitess/VitessOffsetContextTest.java
- src/test/java/io/debezium/connector/vitess/VitessPartitionTest.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
- src/test/java/io/debezium/connector/vitess/VitessSourceInfoStructMakerTest.java
- src/test/java/io/debezium/connector/vitess/VitessTypeTest.java
- src/test/java/io/debezium/connector/vitess/VitessVerifyRecord.java
- src/test/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnTest.java
- src/test/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolverTest.java
- src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
- src/test/java/io/debezium/connector/vitess/connection/VitessColumnValueTest.java
Counterpart to https://github.com/debezium/debezium/pull/4012
https://issues.redhat.com/browse/DBZ-5779
> DBZ-5779 Migrated debezium-connector-vitess to AssertJ

- pom.xml
https://issues.redhat.com/browse/DBZ-2131
> DBZ-2131 Add Apicurion profile

- pom.xml
https://issues.redhat.com/browse/DBZ-5838
> DBZ-5838 Add missing Apicurio converter dependency

- src/main/java/io/debezium/connector/vitess/VitessChangeRecordEmitter.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
- src/test/java/io/debezium/connector/vitess/VitessSourceInfoStructMakerTest.java
Depends on https://github.com/debezium/debezium/pull/4183
> DBZ-2439 DBZ-4669 Align with new formatter/checkstyle

- .github/workflows/sanity-check.yml
https://issues.redhat.com/browse/DBZ-5998
> DBZ-5998 Update the commit message check workflow script

- .github/workflows/contributor-check.yml
- .github/workflows/octocat-commit-check.yml
- .github/workflows/sanity-check.yml
https://issues.redhat.com/browse/DBZ-5998
> DBZ-5998 Synchronize all actions with core CI

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessDatabaseSchema.java
- src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
- src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
- src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
https://issues.redhat.com/browse/DBZ-5743
> DBZ-5743 Introduce a new unicode topic naming strategy

- pom.xml
https://issues.redhat.com/browse/DBZ-6304
> DBZ-6304 Change MySQL Maven coordinates

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
https://issues.redhat.com/browse/DBZ-1973
follow https://github.com/debezium/debezium/pull/4515
> DBZ-1973 Add support for Notifications

- src/main/java/io/debezium/connector/vitess/VitessChangeRecordEmitter.java
* Change in signature of RelationalChangeRecordEmitter
Addresses/Closes DBZ-6366
> DBZ-6366: Code Improvements for skip.messages.without.change

- src/main/java/io/debezium/connector/vitess/VitessChangeEventSourceFactory.java
- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
refer to: https://github.com/debezium/debezium/pull/4614
> DBZ-6416 Add support for Notifications

- src/main/java/io/debezium/connector/vitess/VitessTaskContext.java
https://issues.redhat.com/browse/DBZ-6603
> DBZ-6603 Support for custom tags in the connector metrics

- src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
https://issues.redhat.com/browse/DBZ-6047
Depends on https://github.com/debezium/debezium/pull/4617
> DBZ-6047 Use updated Kafka offset stores

- src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
https://issues.redhat.com/browse/DBZ-6656
> DBZ-6656 Quote table names in Binlog filter builder.

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java
Relates to https://github.com/debezium/debezium/pull/4678
> DBZ-6670 Replace error handler instead of recreate in order to keep retry counter

- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
related to: https://github.com/debezium/debezium/pull/4711
> DBZ-6566 Align code with new blocking snapshot

- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
related to: https://github.com/debezium/debezium/pull/4741
> DBZ-6731 Adapting to SnapshotChangeEventSource changes

- src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
- src/test/java/io/debezium/connector/vitess/TestHelper.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
Added an integration test to verify things work properly for truncate column functionality similar to other connectors (e.g., [mysql](https://github.com/debezium/debezium/blob/main/debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorIT.java#L1447))
> DBZ-6844 Add integration test for truncate column

- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
related to: https://github.com/debezium/debezium/pull/4824
> DBZ-6828 Align code with core

- src/main/java/io/debezium/connector/vitess/converters/VitessCloudEventsProvider.java
- src/main/java/io/debezium/connector/vitess/converters/VitessRecordParser.java
> DBZ-3642 Pass record and metadata when creating parser for CloudEvents conversion

- src/test/docker/Dockerfile
- src/test/docker/local/env.sh
- src/test/docker/local/initial_cluster.sh
- src/test/docker/local/scripts/etcd-up.sh
- src/test/docker/local/scripts/mysqlctl-up.sh
- src/test/docker/local/scripts/utils.sh
- src/test/docker/local/scripts/vtctld-up.sh
- src/test/docker/local/scripts/vtgate-up.sh
- src/test/docker/local/scripts/vtorc-up.sh
- src/test/docker/local/scripts/vttablet-up.sh
- src/test/docker/local/vtorc/config.json
- src/test/java/io/debezium/connector/vitess/TestHelper.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
- src/test/java/io/debezium/connector/vitess/VtctldConnection.java
Upgrade vitess version. Needed to test table copy resuming logic of "snapshots".
> Upgrade to Vitess 17 in itests

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
https://issues.redhat.com/browse/DBZ-4321
Sibling main repository PR https://github.com/debezium/debezium/pull/5081
Supersedes #167
> DBZ-4321 Add `PostProcessor` support

- src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
Depends https://github.com/debezium/debezium/pull/5104
> DBZ-7263 Rebase 2.3 on Kafka 3.5

- src/test/docker/Dockerfile
https://issues.redhat.com/browse/DBZ-7280
> DBZ-7280 use new repository key

- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
related to: https://github.com/debezium/debezium/pull/5138
> DBZ-7311 Permits to execute a blocking snapshot even if snapshot.mode=never

- src/main/java/io/debezium/connector/vitess/VitessChangeEventSourceFactory.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/VitessSnapshotChangeEventSource.java
Related to https://github.com/debezium/debezium/pull/5196
> DBZ-7301 Inject the SnapshotterService

- src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
https://issues.redhat.com/browse/DBZ-7107
Requires - https://github.com/debezium/debezium/pull/5261
> DBZ-7107 Add micro/nano second based timestamps to source info block

- src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
- src/test/resources/vitess_create_tables.ddl
Once changes here are merged https://github.com/debezium/debezium/pull/5599 this integration test will pass.
> DBZ-7265 Add integration test for byte buffer truncation

- src/main/java/io/debezium/connector/vitess/VitessTaskContext.java
relates to: https://github.com/debezium/debezium/pull/5718
> DBZ-8035 Align core changes

- src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
related to: https://github.com/debezium/debezium/pull/5938 that must be merged first
> DBZ-7903 Align core changes

- src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
https://issues.redhat.com/browse/DBZ-8377
> DBZ-8377 Migrate Vitess testsuite to async engine

- pom.xml
- src/test/docker/Dockerfile
https://issues.redhat.com/browse/DBZ-8564
> DBZ-8564 Don't use docker hub for pulls 

- src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
Depends on https://github.com/debezium/debezium/pull/6002
> DBZ-6387 Reflect core refactoring

- src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
Depends on https://github.com/debezium/debezium/pull/6037
> DBZ-8499 Make source info versioned

- src/test/java/io/debezium/connector/vitess/transforms/FilterTransactionTopicRecordsTest.java
- src/test/java/io/debezium/connector/vitess/transforms/RemoveFieldTest.java
- src/test/java/io/debezium/connector/vitess/transforms/ReplaceFieldValueTest.java
- src/test/java/io/debezium/connector/vitess/transforms/TransformsTestHelper.java
These shared resources can overwrite each other and cause failed tests with certain interleaving ie race conditions. 
https://issues.redhat.com/browse/DBZ-9029
> DBZ-9029 Prevent sharing resources between tests

- src/main/java/io/debezium/connector/vitess/VitessConnector.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/main/java/io/debezium/connector/vitess/metrics/VitessSnapshotChangeEventSourceMetrics.java
- src/main/java/io/debezium/connector/vitess/metrics/VitessStreamingChangeEventSourceMetrics.java
- src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
- src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
- src/test/java/io/debezium/connector/vitess/VitessValueConverterTemporalTypesTest.java
- src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java
- src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
related to: https://github.com/debezium/debezium/pull/6430
> DBZ-9020 Align to core changes

- pom.xml
- src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
- src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
- src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
- src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
- src/test/java/io/debezium/connector/vitess/VitessValueConverterTemporalTypesTest.java
- src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java
- src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
requires: https://github.com/debezium/debezium/pull/6496
> DBZ-9110 Align to core changes

- src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
- src/test/java/io/debezium/connector/vitess/VitessHeartbeatImplTest.java
Refer to https://github.com/debezium/debezium/pull/6468 for additional details.
> DBZ-8968: Add support for pluggable ArrayDeque
