debezium/debezium-connector-vitess

src/main/java/io/debezium/connector/vitess/connection/ColumnMetaData.java
src/main/java/io/debezium/connector/vitess/connection/KeyMetaData.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessVerifyRecord.java
src/test/resources/vitess_create_tables.ddl
src/test/resources/vitess_vschema.json

https://issues.redhat.com/browse/DBZ-2578
A Vitess table's primary key will be used as the Kafka message key, or the unique key if the table does not have a primary key.
We will not support multi-column keys because the `flags` provided by VStream doesn't have sufficient information for multi-column keys.

DBZ-2578 Add support for using Vitess primary key as Kafka message key.

---

src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java

https://issues.redhat.com/browse/DBZ-2579
Vitess 8 added Nullable information in the `FIELD` event [flags](https://dev.mysql.com/doc/dev/mysql-server/8.0.12/group__group__cs__column__definition__flags.html#ga0b89f761611b41b80de1f7d50f9b6020). We can make a field in the SourceRecord optional accordingly.
Instead of adding additional integration tests, existing integration tests already cover this case.

DBZ-2579 Add support for Vitess nullable columns

---

src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolver.java
src/test/docker/Dockerfile
src/test/docker/local/create_tables_sharded.sql
src/test/docker/local/create_tables_unsharded.sql
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

- https://issues.redhat.com/browse/DBZ-3100
- https://issues.redhat.com/browse/DBZ-2908
Vitess 9.0.0 GA has fixed the bug on the server-side. Also, the Vitess Connector starts to support Vitess 9.0.0 GA from now on.

DBZ-2908 Remove DECIMAL string sanitisation for Vitess 9 GA

---

pom.xml
src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessTypeTest.java

https://issues.redhat.com/browse/DBZ-3124
Related PRs:
- Website: https://github.com/debezium/debezium.github.io/pull/641
- Vitess Connector documentation: https://github.com/debezium/debezium/pull/2142

DBZ-3124 Add ENUM column type support for Vitess 9.0.0

---

src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessTypeTest.java

https://issues.redhat.com/browse/DBZ-3199
related core PR: https://github.com/debezium/debezium/pull/2167

DBZ-3199 Add support for SET column to Vitess Connector

---

src/test/java/io/debezium/connector/vitess/SourceInfoTest.java

Issue [#2172 in the main Debezium repository](https://github.com/debezium/debezium/pull/2172#issuecomment-799195784) adds a new sequence field
to all `SourceInfo` objects via `AbstractSourceInfo`. This change updates
Vitess' `SourceInfo` schema test to account for this additional field.

DBZ-2911 Add sequence field to Vitess SourceInfo test

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java

Currently provide.transaction.metadata config won't take effect because it is excluded from the config definition.
https://github.com/debezium/debezium-connector-vitess/blob/main/src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java#L134
We need to not exclude it in order to use this this feature.
This fixes https://issues.redhat.com/browse/DBZ-4355

DBZ-4355: Do not exclude provide.transaction.metadata from config

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java
src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

- Add a new config "vitess.keepalive.interval.ms" which configures the gRPC keepalive interval for VStream.
- Add VitessErrorHandler and marks UNAVAILABLE gRPC status error as retriable.
- Fix a race condition issue for integration tests.
This fixes https://issues.redhat.com/browse/DBZ-4389

DBZ-4389: Add keepalive pings and handle retriable exceptions

---

src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolver.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/resources/vitess_create_tables.ddl

Fixes https://issues.redhat.com/browse/DBZ-4403
* Support blob types
* Use string schema (VARCHAR in JDBC) for UINT64 to avoid overflow

DBZ-4403: Support blob types and fix uint64 overflows

---

pom.xml
src/main/java/io/debezium/connector/vitess/Vgtid.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VgtidTest.java

Ensure `Vgtid.toString` method always produces consistent JSON string of the vgtid by making ShardGtids a list (respecting the list order from raw vgtid) and ensure key sequence in each JSON object representing a ShardGtid.
This fixes https://issues.redhat.com/browse/DBZ-4409

DBZ-4409: Enforce consistent JSON serialization of vgtid

---

src/main/java/io/debezium/connector/vitess/SourceInfo.java
src/main/java/io/debezium/connector/vitess/VitessEventMetadataProvider.java
src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
src/main/java/io/debezium/connector/vitess/VitessSourceInfoStructMaker.java
src/main/java/io/debezium/connector/vitess/converters/VitessCloudEventsMaker.java
src/main/java/io/debezium/connector/vitess/converters/VitessRecordParser.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessOffsetContextTest.java
src/test/java/io/debezium/connector/vitess/VitessSourceInfoStructMakerTest.java

Changes in source fields
- "db" value is changed from logical name to keyspace
- "keyspace" field is added
Other changes:
- Make VitessRecordParser constructor public so we can use it directly
- Rename variable VGTID to VGTID_KEY and declare it only once in SourceInfo and reference from all places.
This fixes https://issues.redhat.com/browse/DBZ-4412

DBZ-4412: Fix source fields and add keyspace field

---

src/main/java/io/debezium/connector/vitess/VitessSourceInfoStructMaker.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessSourceInfoStructMakerTest.java

Address https://issues.redhat.com/browse/DBZ-4428
Follow up on https://github.com/debezium/debezium-connector-vitess/pull/58, we have keyspace information in 3 places in Vitess source: db, keyspace and schema. We should clean it up.
This PR remove the `schema` from the Vitess source and override `db` to empty string since in Vitess keyspace is essentially a logical database.
PR to update doc: https://github.com/debezium/debezium/pull/3026

DBZ-4428 Override db and remove schema in Vitess source

---

src/main/java/io/debezium/connector/vitess/SourceInfo.java
src/main/java/io/debezium/connector/vitess/VitessSourceInfoStructMaker.java
src/test/java/io/debezium/connector/vitess/SourceInfoTest.java

Address comments in https://github.com/debezium/debezium-connector-vitess/pull/59
- Fix typo in test 
- Add `keyspace()` in SourceInfo and use that directly instead of `database()`

DBZ-4428 Use keyspace in source info

---

src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java

I identified a bug in Vitess connector column parsing code that results in mislocation of bytes. This is due to incorrect decoding of row.getValues().toStringUtf8() before per-column parsing iteration which cause sub-range copy to fail to find the correct bytes range for each column.
The canonical way to parse VEvent raw values is via [vitess-client](https://github.com/vitessio/vitess/blob/main/java/client/src/main/java/io/vitess/client/cursor/Row.java#L194). However, due to complication of incorporating it (it requires `FieldMap` or `List<Field>`, which is generated in `handleFieldMessage` and can not persist through `decode{Insert,Update,Delete}` methods; this requires `RelationalDatabaseSchema`-compatible schema with Debezium core), we simply implement the equivalent parsing semantics …

DBZ-4657 Fix column value resolving from VEvent

---

src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VgtidTest.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

Transaction ID in TransactionalMessage cannot be null. Therefore, when the decoder is handling BEGIN and COMMIT events and there is no VGTID event received (this can happen in VStream where the VStream Response consists of only BEGIN and COMMIT events), we do not process it.
This change has been tested in our corporate environment.
This fixes https://issues.redhat.com/browse/DBZ-4667
cc @y5w @keweishang @gunnarmorling

DBZ-4667 Fix BEGIN/COMMIT handling when no VGTID was received

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessDatabaseSchema.java
src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessage.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumn.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolver.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VitessColumnValue.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessTypeTest.java
src/test/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnTest.java
src/test/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolverTest.java
src/test/java/io/debezium/connector/vitess/connection/VitessColumnValueTest.java

- Store raw bytes instead of string in `VitessColumnValue` and `ReplicationMessageColumn` used internally in value resolving and converters
- Add bytes support for blob and binary types
- Add support for binary.handling.mode and enable it in config
This fixes: https://issues.redhat.com/browse/DBZ-4705
cc @y5w @keweishang

DBZ-4705 Add bytes support for blob and binary types

---

src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

We found that the following events (raw output using grpcurl from VStream gRPC endpoint) immediately following some row events could cause the connector to output transaction metadata with the wrong GTID.
This is because the transaction id is cached in VStreamOutputMessageDecoder. Whenever there is a normal response that contains `{BEGIN, VGTID and COMMIT}`, the cache will be updated the used according to send out transactional messages.
However, this cache is retained even after the normal response has been processed. If the next time some partial transaction responses like below are received, it will cause these BEGIN and COMMIT events to have the old transaction id from that previously processed response.
```
{  // response 1
"events": [
{
"type": "BEGIN",
"timestamp": "1651088385", …
```

DBZ-5063 Fix inconsistent transaction id

---

pom.xml
src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

When there is a connection reset on Vitess side (e.g. restart VtGate, restart VtTablet, restart mysqlD), sometimes the client will grpc.StatusException: CANCELLED.  Currently we are not treating Cancelled StatusException as retriable which caused the Kafka Connect shuts down the connector eventually.
This error should be retriable.
The fix is relatively straightforward, adding Status.CANCELLED as one of the retrieable error.
The exception you can get are something like below:
2022-08-09 22:54:32,085 INFO  || [Consumer clientId=consumer-1-3, groupId=1] Discovered group coordinator slogs-c-kafka-dev-iad-b771.nebula.tinyspeck.com:9092 (id: 2147482636 rack: null)  [org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]
2022-08-09 22:57:14,000 INFO  Vitess|dev|streaming VStream …

DBZ-5551: Handle Vstream Connection reset

---

pom.xml
src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessPartition.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessPartitionTest.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java

The current Vitess Connector can be launched in two modes:
1. Don't specify Vitess shard info, this will make the connector task to subscribe to ViTess VStream for all shards in the given KeySpace;
2. Specify a particular Vitess shard info, this will make the connector task to subscribe to VStream just for this shard;
In both modes, the connector will only launch one source task (VitessConnectorTask) to do the actual VStream processing.
For a bigger Vitess installation which has many shards, one vitess-dbzium connector with only one source task (mode 1) is not going to be able to sustains the event stream from Vitess.  For mode 2, the operation person needs to manually figure out all the shards in the vitess and manually launch many vitess-dbzium connectors (one connector for one Vitess …

DBZ-5382: Support multiple tasks in vitess connector

---

src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java

When table.include.list was used to only subscribe to changes to a subset of tables in the database, the filtering is currently done in debezium VM.  This is less efficient comparing to the filtering at the VtTablet level.   During VStream subscription, you can specify which tables you are interested, the VtTable will only send the changes to these tables to you.  The benefit of doing filtering in VtTable level is:
1. There are much less network bytes sending over the network,
2. it also has the advantage of avoiding errors related to tables you are not interested.  For example, we had seen errors related to schema mismatch on gh-ost (online schema migration) metadata table, we are not really interested in those tables.  By specifying to subscribe to only the data tables we are interested …

DBZ-5572: Specify table.include.list during VStream subscription

---

src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java

Make 'vstream ended unexpectedly' a retriable error to handle the below
exception:
2022-08-31 20:39:36,039 INFO  Vitess|dev|streaming VStream streaming onError. Status: Status{code=UNKNOWN, description=vstream ended unexpectedly, cause=null}  [io.debezium.connector.vitess.connection.VitessReplicationConnection]
io.grpc.StatusRuntimeException: UNKNOWN: vstream ended unexpectedly
    at io.grpc.Status.asRuntimeException(Status.java:533)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
    at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
    at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
    at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(Dela …

DBZ-5579: Vitess: Handle VStream close unexpectedly

---

src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java

Setup 2 VtTablet servers behind the VtGate, have one of the VtTable have truncated binlogs (e.g. newly bootstrapped from a backup file), have the Debezium connects to the   VtGate using a relatively old Gtids.  On 50% the request will hit one of the VtTablet server which doesn't have the grid history, the Vstream will error out with error messages below.
We should treat this error as retriable error and retry to hopefully route the request to one of the good VtTable which has the gtid.
2022-10-12 10:00:17,440 INFO Vitess|dev|streaming Exception code: UNKNOWN and description: vttablet: rpc error: code = Unknown desc = stream (at source tablet) error @ 027c67a2-c0b0-11ec-8a34-0ed0087913a5:1-11418261,08fb1cf3-0ce5-11ed-b921-0a8939501751:1-1443715,0c4d44de-3bc1-11ed-af99-0ee57f5f6bdb:1-3035408 …

DBZ-5722: Vitess: Handle Vstream error: unexpected server EOF

---

src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java

When dbzium connector went offline for some time and Vitess shard splits during that time (e.g. s1 split into s10 and s11), the current shard list from v$session will have latest (s10, s11) however the shard list persisted Kafka offset topic only contains old shard s1 (pointed at an old position gt1).
When vitess connector restarts, the current logic in VitessConnector.taskConfigs() will use the latest shard list (s10, s11) to do the task assignment and it will use "current" (i.e. tail of the binlog queue) for s10/s11.  The correct behavior should use the old shard (s1) and old position (e.g. gt1) from persisted Kafka offset storage, this way the connector would subscribe to the exact point when it was stopped before.
When the vtgate continue playing the binlog events from vttablet, it …

DBZ-6011 Vitess: Handle the shard list difference between current db shards and persisted shards

---

src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java

With the Vitess connector, the shard setting can only stream a single shard or all shards. It would be helpful to extend this to support a shard list such that gradual scale up/roll out can be done safely with the Vitess connector. This is read in as a CSV list and the accompanying GTIDs can also be specified.
Added unit tests & an integration test verifying we can read multiple shards when they are specified as CSV config.
Note: We implement this feature specifically for the single task mode currently. In a subsequent PR we will implement support for streaming a list of shards and handling multiple tasks. Want to keep the scope of this one just to single task and multi shard streaming.

DBZ-6356 Support streaming a list of shards and accompanying GTIDs

---

src/main/java/io/debezium/connector/vitess/Vgtid.java
src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java

We added support previously for single thread mode for reading in a string of csv shards. Now we extend that to also work with multiple tasks
Added unit tests & acceptance tests for verifying things work as expected when multiple tasks are used with the shard config csv string.
Note: for the registration of the metrics in the integration test, they were always registered under `task_0_1_0` despite the fact that `task_0_2_0` would be the expected name for a connector with 2 max tasks. When I checked the logs the `taskConfigs` function was always being called with 1 even if our config said 2. From what I can tell this is a limitation of the integration tests using the embedded engine, so I just overrode the numTasks for generating the task ID to always be 1.

DBZ-6365 Support streaming a list of shards/gtids with multiple tasks

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java

Use the event processing failure handling mode for handling errors appropriately in the VitessReplicationConnection. This is similar to what is done for [Postgres](https://github.com/debezium/debezium/blob/main/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java#L457). We follow the standard behaviors for error/skip/warn/ignore.
Add a few integration tests for each branch of error/skip/warn/ignore. Check that the error throwable is set/not set appropriately. Use the example use case of an oversized grpc message to be the guaranteed failure (by setting byte max very low).

DBZ-6510 Use event processing failure handling mode in VitessReplicationConnection

---

src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java

This is also similar to [postgres](https://github.com/debezium/debezium/blob/main/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresReplicationConnection.java#L441) where we match on certain error patterns.
As of right now, we know that grpc message size we should use the processing handling mode setting. But for other errors (e.g., connection unavailable) we should preserve the original behavior (reset the connection).

DBZ-6523 Only use event processing failure handling mode on gRPC size error

---

src/main/java/io/debezium/connector/vitess/SourceInfo.java
src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
src/main/java/io/debezium/connector/vitess/VitessSourceInfoStructMaker.java
src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
src/main/java/io/debezium/connector/vitess/connection/DdlMessage.java
src/main/java/io/debezium/connector/vitess/connection/OtherMessage.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessage.java
src/main/java/io/debezium/connector/vitess/connection/TransactionalMessage.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputReplicationMessage.java
src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
src/test/java/io/debezium/connector/vitess/VitessSourceInfoStructMakerTest.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

Add shard to source which is present in row events. Allows downstream users to determine what shard this event is for (we already include keyspace/table so we also include the shard). More context in [DBZ-6617](https://issues.redhat.com/browse/DBZ-6617).

DBZ-6617 Add shard to source

---

src/main/java/io/debezium/connector/vitess/VitessType.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/resources/vitess_create_tables.ddl
src/test/resources/vitess_vschema.json

For VARCHAR columns with a binary collate function (ends in `_bin`) the SourceRecord output type is `BYTES`. In order to stay consistent with the [documentation](https://debezium.io/documentation/reference/stable/connectors/vitess.html#vitess-basic-types) and how [MySQL](https://debezium.io/documentation/reference/stable/connectors/vitess.html#vitess-basic-types) connector handles this, we need to ensure that we have an output type of `STRING`. Add the additional logic needed to do this. There are two cases when QUERY.FIELD type is a VARBINARY
1. The column type may be varchar (this is a varchar column with binary collation) in which case return varchar type
2. Column type is not varchar (e.g., a typical varbinary column), then fall through to next case and return varbinary as usual

DBZ-6748 Make VARCHAR binary collation field types have a VitessType of VARCHAR

---

src/main/java/io/debezium/connector/vitess/Filters.java
src/main/java/io/debezium/connector/vitess/VitessDatabaseSchema.java
src/main/java/io/debezium/connector/vitess/VitessTableIdToStringMapper.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

Schema changes happen per shard, so we should update the schemas accordingly in order to allow for us to correctly decode messages received for each shard without errors. First, add tests to reproduce the issues seen in [DBZ-6775](https://issues.redhat.com/browse/DBZ-6775)/[Zulip](https://debezium.zulipchat.com/#narrow/stream/348255-community-vitess/topic/Vitess.20Connector.20Error), then add the logic needed to resolve this. We add shard as a catalog, and use table string mapper to ensure our include/exclude list doesn't use this catalog/shard value, and we only use it for storing schemas.
Note: I looked into a way around not using the catalog variable as the shard. It seems quite complex to avoid this. There were a couple approaches I evaluated that ended up not being feasible:
1. …

DBZ-6775 Apply schema changes per shard

---

src/main/java/io/debezium/connector/vitess/TableTopicNamingStrategy.java
src/test/java/io/debezium/connector/vitess/TableTopicNamingStrategyTest.java

See [DBZ-6800](https://issues.redhat.com/browse/DBZ-6800) for more details
Add a topic naming strategy that can remove the shard information for users of the vitess connector. Also maintain parity with previous versions such that users do not need to change their topic.prefix and lose connector state.

DBZ-6800 Add TableTopicNamingStrategy

---

src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java

See https://issues.redhat.com/browse/DBZ-6830 these logs can be very frequent for large keyspaces with many multi-response/partial transactions and clutter the logs. Similar to other logic in this class, if a log message could be logged for each message received, it should be a debug level log not info.

DBZ-6830 Switch INFO level to DEBUG for partial & multi-response transactions

---

src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java

It is not possible to skip messages if they are over the [max inbound message size](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#maxInboundMessageSize(int)) on the channel. If an error is received, the channel doesn't continue streaming, so we should always error out and reset.

DBZ-6852 Always fail/reset GRPC channel on error

---

src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java
src/test/java/io/debezium/connector/vitess/VitessErrorHandlerTest.java

Add case to retry on NOT_FOUND status code for down/nonexistent. Also add unit test to make this testable for vitess error handler (and backfill other test cases).
We want to retry to connect in case that tablet is temporarily down/nonexistent, i.e., retry for this exception:
```
2023-09-15 20:01:22,367 ERROR  ||  WorkerSourceTask{id=byuser-connector-23} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:72)
at …
```

DBZ-6939 Retry on NOT_FOUND status code for down/nonexistent tablet

---

src/main/java/io/debezium/connector/vitess/VitessErrorHandler.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessErrorHandlerTest.java

We should retry on all StatusRuntimeException which are a catch all for all errors from the vstream grpc go client.
For throwables that are not that, we can use the super method (retries on IO exceptions only), same as other Debezium connectors (e.g., mysql).

DBZ-6944 Retry all StatusRuntimeException, use super method on others

---

pom.xml
src/main/java/io/debezium/connector/vitess/TablePrimaryKeys.java
src/main/java/io/debezium/connector/vitess/Vgtid.java
src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/SourceInfoTest.java
src/test/java/io/debezium/connector/vitess/TablePrimaryKeysTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VgtidTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessOffsetContextTest.java
src/test/java/io/debezium/connector/vitess/VitessSourceInfoStructMakerTest.java
src/test/java/io/debezium/connector/vitess/VitessVerifyRecord.java
src/test/resources/vitess_create_tables.ddl

Add automatic retry for snapshots.
As detailed in the [table copy RFC ](https://github.com/vitessio/vitess/issues/6277) the last PK value in the VGTID is used for resuming partially complete snapshots. We utilize this for our automatic retries and parse this additional information now being sent by Vitess in the latest version (i.e., including fixes like [this](https://github.com/vitessio/vitess/pull/11103)).
One implementation decision I debated between was switching all of our VGTID parsing logic to instead use the [provided protobuf json converters](https://protobuf.dev/reference/java/api-docs/com/google/protobuf/util/JsonFormat). This would simplify our codebase but also mean the Debezium logic is more tightly coupled with Vitesss/protobuf, so for the latter reason I decided against …

DBZ-7050 Add automatic retry for snapshots

---

src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

Failing test in a different thread doesn't work reliably as JUnit may ignore exceptions (which is how failing test works) in other than main thread.
Do the assert and eventually fail the test in the main test thread.
https://issues.redhat.com/browse/DBZ-7104

DBZ-7104 Fail the test always in the main thread

---

src/test/java/io/debezium/connector/vitess/VitessConnectorTaskTest.java

While working on https://github.com/debezium/debezium/pull/4973 I have noticed the unrelated test failures, one of them being `VitessConnectorTaskTest#shouldReadOffsetsWhenTaskOffsetStorageDisabled`.
The failure was pointing to logs not including the correct error message. Upon closer logs inspection, I have noticed a _very similar_ message is being logged, but the test included an extra message component. I removed it to make the tests green again.
N.B.: I am not very familiar with this codebase, so feel free to discard this PR.

DBZ-6993 Fix VitessConnectorTaskTest failure

---

src/main/java/io/debezium/connector/vitess/connection/MessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

We were using BEGIN timestamp for events. This does not match the [docs](DBZ-7628) which state that ts_ms is the time that the change is _applied_ to the database. This is also inconsistent with other connectors.
We add tests to reproduce the issue of using BEGIN timestamp. Then adjust the functionality to support using COMMIT timestamp instead.
One key part of the correctness of this code is that a the response.getEventsList() will only ever contain 1 transaction or a partial transaction. It will never contain two transactions (this is why we do not need to buffer/store multiple commit timestamps). We know this is the case by the [commit validation in the codebase](https://github.com/debezium/debezium-connector-vitess/blob/main/src/main/java/io/debezium/connector/vitess/connection/VitessR …

DBZ-7628 Use COMMIT time for events, not BEGIN time

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java

related to: https://github.com/debezium/debezium/pull/5401

DBZ-7308 Adapt to core changes

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolver.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessTypeTest.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java
src/test/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolverTest.java
src/test/resources/vitess_create_tables.ddl

Match what the [MySQL](https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-temporal-types) connector does for handling temporal types with the time.precision.mode setting. Previously was converting everything to strings.
Add unit tests for the custom logic for conversion we added. Also add integration test for a table with varying precision levels to test how the behavior changes (e.g., micros or millis based on precision).

DBZ-7773 Implement time.precision.mode for adaptive_time_microseconds and connect

---

src/main/java/io/debezium/connector/vitess/Vgtid.java
src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/main/java/io/debezium/connector/vitess/connection/MessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/docker/Dockerfile
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VgtidTest.java
src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessTypeTest.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
src/test/resources/vitess_create_tables.ddl

Enums/Sets are sent as strings during VStream copy, and during stream are sent as int indexes.
Dynamically handle these two cases.
Soon, there will be a field in newer vitess versions specifying whether it is the actual value or an index. We will add that once it's available in v20 (only v19 released so far)
Fix a brittle itest testing if we increment offset after DDL.
Upgrade to v19 to prep for eventual upgrade to v20.
Note commented where on v20 we will read the enumSetStrings field (allows for smooth upgrades to v20+ for debezium users)
See [zulip](https://debezium.zulipchat.com/#narrow/stream/348255-community-vitess/topic/VStream.20ENUM.20.2F.20SET.20Changes) for more info.

DBZ-7792 Handle enum/set type conversions dynamically based on VStream copy state

---

src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/Gtid.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/GtidTest.java

We can have an edge case where a mysql/vitess host is only used for a single binlog position so it's not a range format host1:1-5 instead just host1:5 so we adapt parsing logic to handle this and reproduce with a test.

DBZ-7905 Handle single position with host in gtid

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

We were previously wrongly using catalog (which stores the shard as done in https://github.com/debezium/debezium-connector-vitess/pull/149) for doing column exclusion. Change to schema (keyspace) and add itest to reproduce issue.

DBZ-7910 Fix column exclude filter type, add itest

---

src/main/java/io/debezium/connector/vitess/Vgtid.java
src/main/java/io/debezium/connector/vitess/transforms/FilterTransactionTopicRecords.java
src/main/java/io/debezium/connector/vitess/transforms/RemoveField.java
src/main/java/io/debezium/connector/vitess/transforms/UseLocalVgtid.java
src/test/java/io/debezium/connector/vitess/VgtidTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/transforms/FilterTransactionTopicRecordsTest.java
src/test/java/io/debezium/connector/vitess/transforms/RemoveFieldTest.java
src/test/java/io/debezium/connector/vitess/transforms/TransformsTestHelper.java
src/test/java/io/debezium/connector/vitess/transforms/UseLocalVgtidTest.java

[DBZ-6721](https://issues.redhat.com/browse/DBZ-6721)
[DBZ-6722](https://issues.redhat.com/browse/DBZ-6722)
Add three new transforms
For connectors where the volume is high (transaction topic is massive), we can drop all messages matching the schema
Generic config for specifying field names (separated by dot '.' for nesting) to remove fields. Can be used to drop any field, in this case we use for transaction.id which can be very large in vitess (contains all shards gtid).
Update VGTID field to only contain vgtid for the shard that the change happened in.
We add this local vgtid transformation (add a hashmap so we don't have to iterate over all shards to do this).
We need to keep the vgtid global for proper offset/state storage so therefore it must be done only at the end as SMT before …

DBZ-6721 & DBZ-6722 Add transforms: local vgtid, remove field, and filter transaction topic

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessHeartbeatImpl.java
src/main/java/io/debezium/connector/vitess/VitessSchemaFactory.java
src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
src/main/java/io/debezium/connector/vitess/connection/HeartbeatMessage.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessage.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessHeartbeatImplTest.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
src/test/java/io/debezium/connector/vitess/VitessSchemaFactoryTest.java
src/test/java/io/debezium/connector/vitess/connection/HeartbeatMessageTest.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

In the case of low volume write tables, we need to be able to emit heartbeat events.
Other connectors do this with a heartbeat query that is run regularly in the upstream database. We don't need to do this since Vitess/VStream provides a helpful flag called [HeartbeatInterval](https://vitess.io/docs/17.0/reference/vreplication/vstream/#heartbeatinterval). We can use the HeartbeatInterval config already present in Debezium core to get this value, parse as seconds, and pass to the VStream API. With this set up, the vstream channel will receive regular heartbeat events from the vtgate indicating liveness. We can dispatch downstream heartbeat events for each we receive.
In order for the heartbeat to be useful, we must know which vitess shards it pertains to (e.g., 8 shards, 2 tasks, each …

DBZ-7962 Add heartbeats

---

src/main/java/io/debezium/connector/vitess/TableTopicNamingStrategy.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/test/java/io/debezium/connector/vitess/TableTopicNamingStrategyTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java

See https://issues.redhat.com/browse/DBZ-8069 for more context on why this needed
See also this Zulip chat on why we went this route https://debezium.zulipchat.com/#narrow/stream/302529-community-general/topic/Separate.20logs.2Fmetrics.20for.20identical.20topic.2Eprefix.20connectors 
Expand our current custom vitess topic naming strategy to support this additional config.

DBZ-8069 Add override.data.change.topic.prefix property to TableTopicNamingStrategy

---

src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessEpochProvider.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionContext.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessEpochProviderTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionContextTest.java

It is non-deterministic/race condition whether or not the `OFFSET_TRANSACTION_ID` is present in the offsets (if we happen to store offsets during a transaction, [it is added since it's not null, otherwise it is not added](https://github.com/debezium/debezium/blob/main/debezium-core/src/main/java/io/debezium/pipeline/txmetadata/TransactionContext.java#L51)). For example if heartbeats are enabled, there is not transaction but we still commit offsets.
Epoch needs to be based on the vgtid we store as for the VGTID_KEY since that is always present in offsets regardless of whether we are in a transaction or not. This fixes an edge case where we saw epoch being set back down to zero because we were getting null for our previous VGTID string. Also fail loudly if we ever see this case again (null …

DBZ-8087 Get previous vgtid from vgtid key in offsets

---

src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessMetadata.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/docker/local/initial_cluster.sh
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessMetadataTest.java

[DBZ-8053](https://issues.redhat.com/browse/DBZ-8053)
In some cases, a Vitess keyspace can have empty shards (shards without tablets). Do the following to handle this:
1. Provide a config exclude.empty.shards (boolean) to enable this behavior
2. If enabled, and no shard list is specified, then auto detect the non-empty shards (shards with tablets)
3. If enabled, and a shard list is specified, then route metadata queries (e.g., get tables) only to those listed shards. Although we could filter this to find the non-empty shards, we want to stay true to what the user configured (and fail loudly if a user is expecting to have a vstream for a certain set of shards, and some of those are empty). However, we can still route the queries such that they use the configured shards and do not risk …

DBZ-8053 Handle empty shards

---

src/main/java/io/debezium/connector/vitess/OffsetValueType.java
src/main/java/io/debezium/connector/vitess/Vgtid.java
src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
src/main/java/io/debezium/connector/vitess/VitessOffsetContext.java
src/main/java/io/debezium/connector/vitess/VitessOffsetRetriever.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/ShardEpochMap.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessEpochProvider.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionContext.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionMetadataFactory.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VgtidTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessOffsetContextTest.java
src/test/java/io/debezium/connector/vitess/VitessOffsetRetrieverTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/ShardEpochMapTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessEpochProviderTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionContextTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionMetadataFactoryTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionStructMakerTest.java

Right now each task simply reads the epoch from its last stored offsets. As seen by the logic for vgtid, we need to be able to handle changes in generation if task offset storage mode is enabled (e.g., task parallelism change or shard subset change). Add this feature by refactoring the logic for vgtid to be more generic so we can do equivalent operations on the shard epochs (when enabled). Add `ShardEpochMap` for centralizing the ser/deser operations of reading the shard epoch map from state & updating it. Operate on VGTID and ShardEpochMap in similar manners to accomplish the same goal of redistributing correctly on task parallelism or shard change.
Note: there is one "TODO" intentionally left in the code: we will soon put out another PR to establish shard lineage and allow for …

DBZ-8154 Make order metadata epoch handle changes to task parallelism & shard set

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/ShardLineage.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessEpochProvider.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionContext.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java
src/test/java/io/debezium/connector/vitess/VitessOffsetContextTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/ShardLineageTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessEpochProviderTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessOrderedTransactionContextTest.java

Add a config feature for inherit epoch. When enabled, the parent shards will be deduced from the hex ranges and we will take the max of the parent shards + 1 to get a newer epoch value. Refactor some things to allow us to read in this config. Also refactor the epoch logic so that our shard epoch map does not drift from the vgtid we receive.
I am hoping to expand our integration test suite in a separate PR to test reshard operations. Since this PR is already substantial putting this out now and will have a separate one for adding reshards to itests.

DBZ-8163 Add inherit epoch feature

---

src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java

Similar to https://github.com/debezium/debezium/pull/5507 this can be logged for every record so users may want to suppress it without losing log values for the other log messages so add a separate logger.

DBZ-8235 Add invalid value logger to VitessValueConverter

---

src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java

The previous code had custom regex filtering which meant it would match all tables with suffixes for the table filter (eg filter is keyspace.table1 and would also match keyspace.table1_suffix1, keyspace.table1_suffix2, keyspace.table1_suffix3). These events would later be filtered out with the call to emit data change event which uses the Debezium Filters construct correctly (it only matches the full table name). This means there could be lots of unnecessary events being requested & deserialized from the vstream. This PR removes this custom regex logic and instead use the Debezium `Filters` to determine which tables to filter fixing this edge case.
This should significantly help with CPU & performance (and cost savings) for keyspaces that have many tables that have the same prefix and …

DBZ-8354 Fix table filter logic for vstream

---

src/main/java/io/debezium/connector/vitess/TableTopicNamingStrategy.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
src/main/java/io/debezium/connector/vitess/connection/DdlMessage.java
src/main/java/io/debezium/connector/vitess/connection/DdlMetadataExtractor.java
src/main/java/io/debezium/connector/vitess/connection/HeartbeatMessage.java
src/main/java/io/debezium/connector/vitess/connection/OtherMessage.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessage.java
src/main/java/io/debezium/connector/vitess/connection/TransactionalMessage.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputReplicationMessage.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/TableTopicNamingStrategyTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/connection/DdlMessageTest.java
src/test/java/io/debezium/connector/vitess/connection/DdlMetadataExtractorTest.java
src/test/resources/vitess_create_tables.ddl
src/test/resources/vitess_vschema.json

Based on feedback on https://github.com/debezium/debezium-connector-vitess/pull/210 creating this PR. Depends on https://github.com/debezium/debezium/pull/5979 (so tests won't pass until that is merged) which allows for publishing schema change events without using the Historized configs/schemas. These are not necessary to use for Vitess VStream so it simplifies the code greatly.
Note: although Vitess DDLs use MySQL syntax, there is a requirement to use the MySQL parser that the [databaseTables](https://github.com/debezium/debezium/blob/44251bc442a8481c8ae3ee9bf70f06b405f328d2/debezium-ddl-parser/src/main/java/io/debezium/antlr/AntlrDdlParser.java#L62) be up to date prior to receiving a DDL event otherwise it is trivially ignored (eg …

DBZ-8325 Emit DDL events

---

pom.xml

4.1.111 has data corruption see [here](https://debezium.zulipchat.com/#narrow/channel/348255-community-vitess/topic/Data.20Corruption.20with.20Kafka.203.2E9.2E0/near/483564599)
I could pin this in debezium-core, but I figure Debezium may want to keep the versions aligned with kafka for those that do not use grpc-java package. Any other connectors that use grpc-java should have this fix as well.

DBZ-8438 Pin netty versions to prevent data corruption

---

src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
src/main/java/io/debezium/connector/vitess/connection/DdlMetadataExtractor.java
src/test/docker/Dockerfile
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/connection/DdlMetadataExtractorTest.java

A few changes to make this DDL logic more fault tolerant
1. Only parse DDLs if that schema history is enabled (otherwise this is unnecessary work)
2. Strip comments to ensure we parse correctly
3. Make table & type fault tolerant so we gracefully handle cases where we didn't parse either
Also fix [DBZ-8432](https://issues.redhat.com/browse/DBZ-8432)
Also dockerfile failing with the apt-key statement so remove that as it's unnecessary

DBZ-8479 Improve DDL parsing logic

---

src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/test/docker/Dockerfile
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

See this [message](https://debezium.zulipchat.com/#narrow/channel/348255-community-vitess/topic/VStream.20ENUM.20.2F.20SET.20Changes/near/435005995) for core logic used. We read this new flag that is set by newer vitess versions to indicate if the enum/set values are strings (previously only in snapshot, going forward is in snapshot & regular phase).
This makes Debezium forward compatible with Vitess upgrades to v20+ so we handle enum/set types correctly.
Without these changes, if https://github.com/debezium/debezium/pull/6079 is merged then tests trivially fail. With these changes and that other PR then tests pass.
Right now, since the main upgrade isn't merged, tests trivially pass (does not use any of the new code)

DBZ-8561 Correctly handle enum/set types in Vitess v20+

---

src/main/java/io/debezium/connector/vitess/SourceInfo.java
src/main/java/io/debezium/connector/vitess/VitessStreamingChangeEventSource.java
src/main/java/io/debezium/connector/vitess/connection/MessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageProcessor.java
src/main/java/io/debezium/connector/vitess/connection/TransactionalMessage.java
src/main/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoder.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/main/java/io/debezium/connector/vitess/pipeline/txmetadata/Gtid.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java
src/test/java/io/debezium/connector/vitess/connection/TransactionalMessageTest.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java
src/test/resources/vitess_create_tables.ddl

We found an edge case described in [DBZ-8594](https://issues.redhat.com/browse/DBZ-8594)
There's another possible way to implement this: Modify VitessChangeRecordEmitter - we could modify our implementation to set the offset before emitting the final delete record [here](https://github.com/debezium/debezium/blob/main/debezium-core/src/main/java/io/debezium/relational/RelationalChangeRecordEmitter.java#L184). This would be possible but it seemed like a more custom solution, we'd prefer to be as standard as possible. Let me know if you think this is preferred. I think VitessOffsetContext would be called there to resetVgtid (and maybe in create/delete/update functions as well). The thing I don't like is we don't get the bug fixes or changes from the class we inherit from so we have to …

DBZ-8594 Prevent data loss when primary key update is last operation in transaction

---

src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

We didn't have full test coverage for all string data types, in particular one missed was json. Verify truncation for all string data types

DBZ-8663 Modify itest to test truncation for all string data types

---

src/main/java/io/debezium/connector/vitess/VitessType.java
src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessTypeTest.java
src/test/resources/vitess_create_tables.ddl

Ticket: [DBZ-8679](https://issues.redhat.com/browse/DBZ-8679)
We worked on this previously in [DBZ-6748](https://issues.redhat.com/browse/DBZ-6748) to do this for varchars. However, there are other string types (e.g., text, enum, set) that also experience the same issue (binary collation only affects ordering in mysql but affects how the vstream sends the data and ends up that the final change data value is treated as byte array). Added unit & integration tests to confirm the issue with this behavior. Introduced additional logic primarily in VitessType to allow for these data types to still be output as strings.

DBZ-8679 Send string types with binary collation as strings

---

src/main/java/io/debezium/connector/vitess/VitessOffsetRetriever.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTaskTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java

https://issues.redhat.com/browse/DBZ-8719
Add tests to verify that when we scale down tasks that we read the last stored offsets (we already have tests that verify this for the scale out case).

DBZ-8719 Test scaling down reads last offsets

---

src/main/java/io/debezium/connector/vitess/TableTopicNamingStrategy.java
src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/docker/Dockerfile
src/test/docker/local/initial_cluster.sh
src/test/docker/local/scripts/vttablet-up.sh
src/test/java/io/debezium/connector/vitess/TableTopicNamingStrategyTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

[DBZ-8775](https://issues.redhat.com/browse/DBZ-8775)
https://github.com/debezium/debezium/pull/6224 must first be merged (tests will fail trivially until then, once it's merged all tests will pass)
This was added in [Vitess v21](https://github.com/vitessio/vitess/issues/16477).
Add support to pass in this VStream API flag.
Since these heartbeat tables are regular data change events, add a config that allows user to pass in a regex exclude list for the override data change topic config (ie multiple connectors in the same DB streaming the same heartbeat table should output to separate topics).

DBZ-8775 Add support for new VStream feature: streamKeyspaceHeartbeats

---

src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/docker/local/initial_cluster.sh
src/test/docker/local/scripts/vttablet-up.sh
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java

[DBZ-8824](https://issues.redhat.com/browse/DBZ-8824)
Adds an integration test for keyspace heartbeats during a copy. In particular we need to verify that heartbeat events are not sent during the [catch up phase](https://github.com/vitessio/vitess/issues/6277) of a vstream copy. This is so that downstream users do not wrongfully trigger jobs during a snapshot (thinking data is all caught up).
A few other changes
1. Remove unused variables
2. DRY up some code
3. Extend some test utilities
4. Isolate heartbeat keyspace

DBZ-8824 Add integration test for keyspace heartbeats during snapshot

---

src/main/java/io/debezium/connector/vitess/VitessChangeRecordEmitter.java
src/main/java/io/debezium/connector/vitess/VitessMetadata.java
src/main/java/io/debezium/connector/vitess/VitessValueConverter.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessage.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumn.java
src/main/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolver.java
src/test/java/io/debezium/connector/vitess/AbstractVitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/TestHelper.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTemporalTypesTest.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java
src/test/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnTest.java
src/test/java/io/debezium/connector/vitess/connection/ReplicationMessageColumnValueResolverTest.java

[DBZ-8826](https://issues.redhat.com/browse/DBZ-8826)
We should also be able to output as strings for temporal types (time, date, datetime). Accomplish this by using the TemporalPrecisionMode.ISO_STRING mode. Note: In order to prevent loss of information, we customize the behavior compared to other connectors. Specifically, we want to ensure that impossible values like 0000-00-00 are still sent identical to their upstream values. Other connectors convert to a timestamp then back to a string (so converting 0000-00-00 fails). Instead, we do not do this conversion, and simply send the string value sent by MySQL.
Note: later we could modify debezium core to have a mode called RAW_STRING that does this. I went with this approach to keep things contained with vitess-connector and to not block …

DBZ-8826 Support temporal precision mode for strings

---

src/main/java/io/debezium/connector/vitess/VitessConnector.java
src/main/java/io/debezium/connector/vitess/VitessMetadata.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VitessConnectorTest.java
src/test/java/io/debezium/connector/vitess/VitessMetadataTest.java
src/test/java/io/debezium/connector/vitess/pipeline/txmetadata/VitessEpochProviderTest.java

This is supported by [Vitess](https://vitess.io/docs/21.0/user-guides/configuration-advanced/comment-directives/#workload-name-workload_name) for tracking which application is issuing the queries. Add this workload name info in every query we use (refactor things so all queries are issued from VitessMetadata).
Also clarify one test I noticed can be stronger assertion (assert epoch incremented for all shards).

DBZ-8861 Add workload name to all queries issued by Debezium

---

src/main/java/io/debezium/connector/vitess/VitessConnector.java

https://issues.redhat.com/browse/DBZ-9008
We were omitting the stack trace, use logger.error to include it as throwable arg.

DBZ-9008 Log stack trace when connection fails

---

src/main/java/io/debezium/connector/vitess/VitessConnectorConfig.java
src/main/java/io/debezium/connector/vitess/connection/VitessReplicationConnection.java
src/test/java/io/debezium/connector/vitess/VitessConnectorConfigTest.java

[DBZ-9014](https://issues.redhat.com/browse/DBZ-9014)
Make load balancing policy configurable.
The default is pick first (what it does currently when not specified). Round robin is also supported. Others may be added as well, so future proof it by keeping the config open as a string (with validation that the policy is supported for the current version).

DBZ-9014 Make load balancing policy configurable

---

src/test/docker/Dockerfile

vitess/base hasn't been updated since v19 and we don't need it since the newer lite version comes with these packages already present in those dirs

Simplify dockerfile for itests

---

src/main/java/io/debezium/connector/vitess/VitessConnectorTask.java
src/main/java/io/debezium/connector/vitess/VitessDatabaseSchema.java
src/test/java/io/debezium/connector/vitess/VitessBigIntUnsignedTest.java
src/test/java/io/debezium/connector/vitess/VitessChangeRecordEmitterTest.java
src/test/java/io/debezium/connector/vitess/VitessConnectorIT.java
src/test/java/io/debezium/connector/vitess/VitessReplicationConnectionIT.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTemporalTypesTest.java
src/test/java/io/debezium/connector/vitess/VitessValueConverterTest.java
src/test/java/io/debezium/connector/vitess/connection/VStreamOutputMessageDecoderTest.java

Currently, the `CustomConverterRegistry` is retrieved from `ConnectorConfiguration`. This can lead to some issues:
- Multiple points of retrieval for the registry
- Mixing configuration with business logic
Use the `ServiceRegistry` to retrieve the `CustomConverterRegistry`.
#depends https://github.com/debezium/debezium/pull/6553

DBZ-8966 use CustomConverter in serviceRegistry and remove usage in ConnectorConfiguration
